spring:
  application:
    name: order-management-system
  # autoconfigure:
  #   exclude: 
  #     - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    '[org.springframework.transaction]': DEBUG